# Generated by Django 4.0.3 on 2024-02-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAuthentication', '0002_alter_user_address_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, help_text='Only .png and .jpg are accepted', null=True, upload_to='eis/files/%y', validators=[django.core.validators.FileExtensionValidator('.png,.jpg')]),
        ),
    ]
