# Generated by Django 4.0.3 on 2024-02-02 12:46

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.CharField(default='', max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('address', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('accreditation_status', models.CharField(default='', max_length=255)),
                ('principal_name', models.CharField(default='', max_length=255)),
                ('principal_email', models.EmailField(default='', max_length=254, unique=True)),
                ('principal_phone_number', models.CharField(default='', max_length=20)),
                ('files', models.ImageField(blank=True, help_text='Only .pdf are accepted', null=True, upload_to='eis/files/%y', validators=[django.core.validators.FileExtensionValidator('.pdf')])),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
