# Generated by Django 4.0.3 on 2022-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='thumbnail',
            field=models.ImageField(help_text='Provide the image of your Company', null=True, upload_to=''),
        ),
    ]
