# Generated by Django 4.0.3 on 2022-04-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCompany', '0005_company_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the Company:'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(help_text='Owner of Company:', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
