# Generated by Django 4.0.3 on 2022-04-27 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCompany', '0006_alter_company_name_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(help_text='At what time your company ends?. Expected in PM', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(help_text='At what time your company starts?. Expected in AM', null=True),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(editable=False, null=True)),
                ('review_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=150)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCompany.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
