# Generated by Django 4.0.3 on 2022-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0007_alter_company_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
