# Generated by Django 4.0.3 on 2022-04-28 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCompany', '0009_event_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userserviceorders', to=settings.AUTH_USER_MODEL),
        ),
    ]
