# Generated by Django 4.0.3 on 2022-04-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0010_service_ordered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='following',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MCompany.category'),
        ),
    ]
