# Generated by Django 4.0.3 on 2022-04-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0011_category_company_following_company_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='category',
            new_name='catego',
        ),
    ]
