# Generated by Django 4.0.3 on 2022-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0013_remove_company_catego_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
