# Generated by Django 4.0.3 on 2022-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0014_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Business Email'),
        ),
    ]
