# Generated by Django 4.0.3 on 2022-04-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0016_remove_event_email_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='following',
            new_name='followers',
        ),
    ]
