# Generated by Django 4.0.3 on 2022-04-29 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0017_rename_following_company_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='going',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='total_sits',
            field=models.PositiveIntegerField(help_text='Total no of people that can participate in this event.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='sits',
            field=models.PositiveIntegerField(help_text='No of people enrolling for this service.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
