# Generated by Django 4.0.3 on 2022-04-29 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0018_service_going_service_total_sits_alter_service_sits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='going',
        ),
        migrations.RemoveField(
            model_name='service',
            name='total_sits',
        ),
        migrations.AddField(
            model_name='event',
            name='going',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_sits',
            field=models.PositiveIntegerField(help_text='Total no of people that can participate in this event.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
