# Generated by Django 4.0.3 on 2022-04-29 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MCompany', '0019_remove_service_going_remove_service_total_sits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_plan', models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Month', '3 Month'), ('Yearly', 'Yearly')], max_length=50, null=True, verbose_name='Name of the Company:')),
                ('price', models.DecimalField(decimal_places=2, default=40, max_digits=6, max_length=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Owner of Company:', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCompany.company')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_plan', models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Month', '3 Month'), ('Yearly', 'Yearly')], max_length=50, null=True, verbose_name='Name of the Company:')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('starting_time', models.TimeField(help_text='At what time your company starts?. Expected in AM', null=True)),
                ('endinng_time', models.TimeField(help_text='At what time your company ends?. Expected in PM', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=40, max_digits=6, max_length=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Owner of Company:', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCompany.company')),
            ],
        ),
    ]
