# Generated by Django 4.0.3 on 2022-04-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0020_gymmembership_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Futsal', 'Futsal')], max_length=50, null=True),
        ),
    ]
