# Generated by Django 4.0.3 on 2022-04-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0021_alter_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='paying_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCompany.gymplan'),
        ),
    ]
