# Generated by Django 4.0.3 on 2022-04-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0022_gymplan_alter_gymmembership_paying_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=4, null=True),
        ),
    ]
