# Generated by Django 4.0.3 on 2022-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0024_remove_category_price_gymplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmembership',
            name='price',
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='joining_time',
            field=models.TimeField(null=True),
        ),
    ]
