# Generated by Django 4.0.3 on 2022-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0025_remove_gymmembership_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmembership',
            name='coming_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='joining_time',
            field=models.DateTimeField(null=True),
        ),
    ]
