# Generated by Django 4.0.3 on 2022-04-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0029_company_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, max_length=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='paying_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MCompany.bookingplan'),
        ),
    ]
