# Generated by Django 4.0.3 on 2022-04-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0032_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Book Now', 'Book Now')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MCompany.company'),
        ),
    ]
