# Generated by Django 4.0.3 on 2022-04-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0033_alter_booking_availability_alter_booking_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='endinng_time',
            new_name='ending_time',
        ),
    ]
