# Generated by Django 4.0.3 on 2022-04-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0034_rename_endinng_time_booking_ending_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('starting_time',)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='ending_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
