# Generated by Django 4.0.3 on 2022-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0036_alter_booking_ending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Book Now', 'Book Now')], default='Book Now', max_length=100),
        ),
    ]
