# Generated by Django 4.0.3 on 2022-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0037_alter_booking_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bookingprice',
            field=models.IntegerField(null=True),
        ),
    ]
