# Generated by Django 4.0.3 on 2022-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0040_remove_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='office_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
