# Generated by Django 4.0.3 on 2022-04-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0041_company_office_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
    ]
