# Generated by Django 4.0.3 on 2022-04-30 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCompany', '0043_location_remove_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MCompany.location'),
        ),
    ]
