# Generated by Django 4.0.3 on 2022-04-24 14:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MCompany', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('Free', 'Free'), ('Enterprise', 'Enterprise'), ('Professional', 'Professional')], default='Free', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, max_length=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_plan', models.PositiveIntegerField(help_text='Monthly plan in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_countdown', models.DateTimeField(auto_now_add=True)),
                ('end_countdown', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MCompany.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemebershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MUtilities.membership')),
            ],
        ),
    ]
