# Generated by Django 4.0.3 on 2022-04-24 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUtilities', '0002_alter_membership_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='monthly_plan',
            field=models.PositiveIntegerField(help_text='Monthly plan in months', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
