# Generated by Django 4.0.3 on 2022-04-25 14:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUtilities', '0003_alter_membership_monthly_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='company',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='monthly_plan',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='paying_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('2'))]),
        ),
    ]
