# Generated by Django 4.0.3 on 2022-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUtilities', '0004_remove_membership_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='paying_plan',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=4, null=True),
        ),
    ]
