# Generated by Django 4.0.3 on 2022-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUtilities', '0005_alter_membership_paying_plan_alter_membership_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='paying_plan',
            field=models.CharField(choices=[('None', 'None'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
    ]
